package com.yasser.mazr3a_task.model

data class Order(
    val billingPerson: BillingPerson,
    val couponDiscount: Int,
    val createDate: String,
    val createTimestamp: Int,
    val customerId: Int,
    val customerTaxExempt: Boolean,
    val customerTaxIdValid: Boolean,
    val disableAllCustomerNotifications: Boolean,
    val discount: Int,
    val email: String,
    val externalFulfillment: Boolean,
    val fulfillmentStatus: String,
    val giftCardDoubleSpending: Boolean,
    val giftCardRedemption: Int,
    val hidden: Boolean,
    val id: String,
    val items: List<Item>,
    val membershipBasedDiscount: Int,
    val orderNumber: Int,
    val paymentMethod: String,
    val paymentParams: PaymentParams,
    val paymentStatus: String,
    val refundedAmount: Int,
    val reversedTaxApplied: Boolean,
    val subtotal: Int,
    val tax: Int,
    val total: Int,
    val totalAndMembershipBasedDiscount: Int,
    val totalBeforeGiftCardRedemption: Int,
    val updateDate: String,
    val updateTimestamp: Int,
    val usdTotal: Double,
    val vendorOrderNumber: String,
    val volumeDiscount: Int
)